### PR TITLE
fix/164: Show pagination when Sort by Order is clicked

### LINKED ISSUE #164: Pagination is hidden/disabled when "Sort by Order" is clicked
### Describe the bug

Pagination is hidden/disabled when "Sort by Order" is clicked. As per investigation by @dkotter, having the `title` value in `orderby` causes this.

props @tlovett1 @dkotter for raising and investigating the bug.

### Steps to Reproduce

1. Create 5-6 pages
2. Under Screen options in admin screen, set Pagination to 2
3. Reload page and observe that pagination is visible.
4. Click **sort by Order** and observe pagination is not visible.

The expectation is that pagination should be visible when **Sort by Order** is clicked.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Sidsector9**
Closes #164

### Description of the Change

In this PR, we additionally send `posts_per_page` as `-1` when "Sort By Order" is clicked to enable pagination.

### Changelog Entry

> Fixed - Hidden pagination in admin screen when Sort by Order is clicked

### Credits

Props @tlovett1 @dkotter @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by dkotter — COMMENTED** [review]
While this does appear to fix the pagination issue, what I'm seeing is it will no longer show the page heirarchy. For instance, if I have a parent page with multiple child pages, on the main list view, those are shown as nested beneath the parent. If I click on `Sort by order` prior to this fix, that nesting is still shown, though pagination doesn't show. With the changes in this PR, if I click on `Sort by order`, pagination now shows but the nesting heirarchy is lost

**Comment by Sidsector9** [comment]
@dkotter that's a good catch. I took an alternative approach and tested it with child, as well as child of child elements. Can you take a look?

File: simple-page-ordering.php [hunk 1]
```diff
@@ -168,10 +168,26 @@ public static function load_edit_screen() {
...
 			add_action( 'admin_head', array( __CLASS__, 'admin_head' ) );
 		}
 
+		/**
+		 * This is to enable pagination.
+		 *
+		 * @param WP_Query $query The WP_Query instance (passed by reference).
+		 */
+		public static function filter_query( $query ) {
+			$is_simple_page_ordering = isset( $_GET['id'] ) ? 'simple-page-ordering' === sanitize_text_field( wp_unslash( $_GET['id'] ) ) : false;
```
Comment (peterwilsoncc) [inline simple-page-ordering.php]: No need to sanitize or unslash when comparing to a string that requires neither.

```suggestion
			// phpcs:ignore WordPress.Security.NonceVerification.Recommended
			$is_simple_page_ordering = isset( $_GET['id'] ) ? 'simple-page-ordering' === $_GET['id'] : false;
```

File: simple-page-ordering.php [hunk 2]
```diff
@@ -168,10 +168,26 @@ public static function load_edit_screen() {
...
+
+			if ( ! $is_simple_page_ordering ) {
+				return;
+			}
+
+			$query->set( 'posts_per_page', -1 );
```
Comment (peterwilsoncc) [inline simple-page-ordering.php:193]: I'm unclear how this works, it appears to remove paging but forces it. Are you able to explain to me what I am missing?

**Review by peterwilsoncc — COMMENTED** [review]
This will affect all queries on the page, not just the main query for the list table.

It's probably going to need:

```php
			if ( ! $query->is_main_query() ) {
				return;
			}
```

File: simple-page-ordering.php (hunk 2 above)
Comment (Sidsector9) [reply simple-page-ordering.php:193]: Sure. Comparing the issue with how clicking "All" works, the reason why "Sort by Order" does not work is because it adds a LIMIT to the query here:

https://github.com/WordPress/wordpress-develop/blob/d8206d2167f2c082258f31db163289bae3682e06/src/wp-includes/class-wp-query.php#L2745

To avoid that and make the "Sort By Order" work similarly to "All", we set 'nopaging' to `true` here:
https://github.com/WordPress/wordpress-develop/blob/d8206d2167f2c082258f31db163289bae3682e06/src/wp-includes/class-wp-query.php#L1988 by setting `posts_per_page` to `-1`.

**Review by peterwilsoncc — APPROVED** [review]
LGTM and passes manual testing.

The E2E tests failed on the first run but it appears to have been a glitch as they passed on the second run.
